### ISSUE TITLE
add 3xTg pathology data

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#83]
Details:
[This spreadsheet](https://docs.google.com/spreadsheets/d/1B3ZMReC7nR2CGgpFNJuxJTj__lF2h6dt/edit#gid=1108411940) details the field mapping for pathology data.

Unlike 5xFAD, individual data points are NOT associated with individual biospecimen IDs, however they should still be treated as separate data points.

The control strain is different for 3xTg.

**Comment by sharlagelfand** [comment]
I have a start on adding in the data (including linking the pooled metadata) - just want to confirm that B6129F3 is the control strain?

I think we discussed this a bit before, but right now in the app you can select all of the models, e.g. both 5xFAD with C57BL/6J and 3xTG with B6129F3:

<img width="324" alt="Screen Shot 2022-03-02 at 1 11 35 PM" src="https://user-images.githubusercontent.com/15895337/156422595-fc884811-8206-44cf-ab83-1b69bba35514.png">

Do we want to update this so that only 5xFAD and 3xTg are options, and selecting one would also show the panel for its control, too? If so, I can create a new issue for that!

**Comment by annagree** [comment]
@ryaxley Can you reach out to UCI on Slack and confirm that B6129F3 is the proper control for 3xTg-AD?

**Comment by annagree** [comment]
@sharlagelfand I like the simplicity of reducing the list so only 5xFAD and 3xTg are options, and the matched control shows up with it. Thanks for making a new issue!

**Comment by annagree** [comment]
@sharlagelfand the team has labeled these as B6129F3 (F3 is the generation), but they have now realized that they don't want to include the F3, and just want it to be B6129. They're going to redo the metadata and upload a new version.

**Comment by sharlagelfand** [comment]
For now, let's manually update B6129F3 to B6129, and then when the updated file is available, take out the recoding and add the new file.

**Comment by annagree** [comment]
@sharlagelfand It sounds like this is the only time they'll be adding B6129 data in this format. Is it a problem to just keep the manual updating logic permanently in the code or should we have the team update the name in the file?

Another note- there is no 8 month data for 3xTg-AD, so we are good to go on that front.

**Comment by sharlagelfand** [comment]
@annagree No problem to keep the manual updating logic permanently! 

Thanks for checking on the 8 month data.
